# This rule is not used by the project secret-distributor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to secdist.etzba.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-distributor
    app.kubernetes.io/managed-by: kustomize
  name: distribution-viewer-role
rules:
- apiGroups:
  - secdist.etzba.com
  resources:
  - distributions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secdist.etzba.com
  resources:
  - distributions/status
  verbs:
  - get
